# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 974)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabCtr = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabCtr.setGeometry(QtCore.QRect(10, 0, 1131, 971))
        self.MainTabCtr.setIconSize(QtCore.QSize(32, 32))
        self.MainTabCtr.setObjectName("MainTabCtr")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pts_leagueBox = QtWidgets.QComboBox(self.tab)
        self.pts_leagueBox.setGeometry(QtCore.QRect(10, 30, 181, 22))
        self.pts_leagueBox.setObjectName("pts_leagueBox")
        self.pts_yearBox = QtWidgets.QComboBox(self.tab)
        self.pts_yearBox.setGeometry(QtCore.QRect(200, 30, 181, 22))
        self.pts_yearBox.setObjectName("pts_yearBox")
        self.pts_browser = QtWidgets.QTextBrowser(self.tab)
        self.pts_browser.setGeometry(QtCore.QRect(10, 70, 1071, 671))
        self.pts_browser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pts_browser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.pts_browser.setObjectName("pts_browser")
        self.MainTabCtr.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ga_leagueBox = QtWidgets.QComboBox(self.tab_2)
        self.ga_leagueBox.setGeometry(QtCore.QRect(10, 30, 231, 22))
        self.ga_leagueBox.setObjectName("ga_leagueBox")
        self.ga_yearBox = QtWidgets.QComboBox(self.tab_2)
        self.ga_yearBox.setGeometry(QtCore.QRect(270, 30, 241, 22))
        self.ga_yearBox.setObjectName("ga_yearBox")
        self.ga_optionBox = QtWidgets.QComboBox(self.tab_2)
        self.ga_optionBox.setGeometry(QtCore.QRect(550, 30, 221, 22))
        self.ga_optionBox.setObjectName("ga_optionBox")
        self.ga_browser = QtWidgets.QTextBrowser(self.tab_2)
        self.ga_browser.setGeometry(QtCore.QRect(10, 80, 1091, 681))
        self.ga_browser.setObjectName("ga_browser")
        self.MainTabCtr.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 350, 701, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.charts_test = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.charts_test.setContentsMargins(0, 0, 0, 0)
        self.charts_test.setObjectName("charts_test")
        self.charts_show = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.charts_show.setObjectName("charts_show")
        self.charts_test.addWidget(self.charts_show)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(40, 40, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 40, 201, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(500, 40, 221, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 90, 621, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(260, 260, 481, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.MainTabCtr.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 20, 191, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_5.setGeometry(QtCore.QRect(250, 20, 191, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(40, 90, 201, 191))
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(280, 90, 121, 191))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 90, 121, 191))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(40, 330, 521, 281))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_7)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5.addWidget(self.widget_2)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(40, 630, 521, 281))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget_8)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6.addWidget(self.widget_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser.setGeometry(QtCore.QRect(600, 330, 501, 581))
        self.textBrowser.setObjectName("textBrowser")
        self.MainTabCtr.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 30, 191, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(20, 32, 61, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 251, 231))
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setObjectName("label_13")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(330, 90, 121, 191))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(460, 90, 121, 191))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(20, 330, 121, 191))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(150, 330, 121, 191))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_10.addWidget(self.label_21)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(330, 330, 121, 191))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_11.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_11.addWidget(self.label_23)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(460, 330, 121, 191))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_12.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(20, 550, 561, 321))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_4 = QtWidgets.QWidget(self.verticalLayoutWidget_15)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_13.addWidget(self.widget_4)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(600, 90, 491, 781))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_5 = QtWidgets.QWidget(self.verticalLayoutWidget_16)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_14.addWidget(self.widget_5)
        self.MainTabCtr.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainTabCtr.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainTabCtr.setTabText(self.MainTabCtr.indexOf(self.tab), _translate("MainWindow", "积分"))
        self.MainTabCtr.setTabText(self.MainTabCtr.indexOf(self.tab_2), _translate("MainWindow", "射手榜/助攻榜"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "VS"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.MainTabCtr.setTabText(self.MainTabCtr.indexOf(self.tab_3), _translate("MainWindow", "单场统计"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "name"))
        self.label_9.setText(_translate("MainWindow", "coutry"))
        self.label_10.setText(_translate("MainWindow", "liverpool"))
        self.label_11.setText(_translate("MainWindow", "England"))
        self.MainTabCtr.setTabText(self.MainTabCtr.indexOf(self.tab_4), _translate("MainWindow", "球队数据"))
        self.label_12.setText(_translate("MainWindow", "搜索"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "name"))
        self.label_15.setText(_translate("MainWindow", "coutry"))
        self.label_16.setText(_translate("MainWindow", "M，Salh"))
        self.label_17.setText(_translate("MainWindow", "Eygpt"))
        self.label_18.setText(_translate("MainWindow", "Birth"))
        self.label_19.setText(_translate("MainWindow", "club"))
        self.label_20.setText(_translate("MainWindow", "1992.6.18"))
        self.label_21.setText(_translate("MainWindow", "Liverpool"))
        self.label_22.setText(_translate("MainWindow", "Height"))
        self.label_23.setText(_translate("MainWindow", "Weight"))
        self.label_24.setText(_translate("MainWindow", "175"))
        self.label_25.setText(_translate("MainWindow", "70"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.MainTabCtr.setTabText(self.MainTabCtr.indexOf(self.tab_5), _translate("MainWindow", "球员"))

